eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8888/eureka}
  instance:
    preferIpAddress: true



okta:
  oauth2:
    issuer: https://dev-34786947.okta.com/oauth2/default
    audience: api://default
